Update action.yml

diff --git a/.github/workflows/patch-susfs/action.yml b/.github/workflows/patch-susfs/action.yml
--- a/.github/workflows/patch-susfs/action.yml
+++ b/.github/workflows/patch-susfs/action.yml
@@ -262,19 +262,19 @@ runs:
           fi
 
           # Upgrade 1.5.13
-          if grep -q "CMD_SUSFS_ADD_SUS_MAP" "drivers/kernelsu/core_hook.c"; then
-            cp /tmp/Patches/Patch/susfs_upgrade_to_1513_${{ env.KERNEL_VERSION }}.patch ./
-            patch -p1 < susfs_upgrade_to_1513_${{ env.KERNEL_VERSION }}.patch || true
-            echo "================="
-            echo "=Upgraded 1.5.13="
-            echo "================="
+#          if grep -q "CMD_SUSFS_ADD_SUS_MAP" "drivers/kernelsu/core_hook.c"; then
+#            cp /tmp/Patches/Patch/susfs_upgrade_to_1513_${{ env.KERNEL_VERSION }}.patch ./
+#            patch -p1 < susfs_upgrade_to_1513_${{ env.KERNEL_VERSION }}.patch || true
+#            echo "================="
+#            echo "=Upgraded 1.5.13="
+#            echo "================="
 
-            REJ_FOUND "1.5.13"
-          else
-            echo "============================================================"
-            echo "=Your kernelsu fork cannot supported SuSFS 1.5.13, Skipped.="
-            echo "============================================================"
-          fi
+#            REJ_FOUND "1.5.13"
+#          else
+#            echo "============================================================"
+#            echo "=Your kernelsu fork cannot supported SuSFS 1.5.13, Skipped.="
+#            echo "============================================================"
+#          fi
 
       - name: Updated SUSFS Patch Fixed
         if: env.SUSFS_ENABLE == 'true' && env.SUSFS_UPDATE == 'true' && env.SUSFS_SKIP != 'true'
